### ISSUE TITLE
Read in hess and/or gbw files from a previous Orca calculation

### ISSUE THREAD

**Issue by tanoury1** [eljost/pysisyphus#136]
Hi,
I would like to read in a hessian file generated from an Orca TS optimization which I performed prior to using pysisyphus.  The correct syntax for Orca is:

%geom
inhess Read
InHessName "filename.hess"
end

However, when I use:
blocks: "%geom inhess Read InHessName "filename.hess" end"
I get an error message because the code expects the end of the blocks section at the second set of double quotes.  Using %moinp in Orca also requires having the file name in double quotes.  Is there a way to do this in the current version of pysisyphus?

Thank you,
Jerry

**Comment by eljost** [comment]
Hi Jerry,
what version are you using? In the current `dev`branch calculated Hessians are saved to HDF5 files, which can in turn be specified as argument to `hessian_initial`. I'll include an example tomorrow.

If you want to carry out the TS-optimization in pysisyphus including `blocks: %geom inhess ...` is not the right approach. Pysisyphus handles the TS-optimization, ORCA only calculates the energy and its derivatives, e.g., gradient and/or Hessian. So you must tell pysisyphus what Hessian to use, which is easily possible. Below you can find an example.
[orca_tsopt_example.zip](https://github.com/eljost/pysisyphus/files/6511354/orca_tsopt_example.zip)

In case you are forced to nest the double quotation marks just use single quotation marks ('...') for the outer ones. Like this
```
block: '%geom inhessname "test.hess" end'
```
Let me know if this solves your issues! I try to make a new release soon, otherwise its a good idea to use the current dev branch.

All the best
Johannes

**Comment by tanoury1** [comment]
Hi Johannes,
Thank you for the quick reply.  I downloaded the dev version, then
installed it with: 'pip install . qcengine pyscf ase --user'.  I am using
python 3.8.0.

However, I got the following error at the end:
Successfully built pysisyphus
ERROR: indra 1.15.2 has requirement ndex2==2.0.1, but you'll have ndex2
3.3.1 which is incompatible.
ERROR: indra 1.15.2 has requirement pysb<=1.9.1,>=1.3.0, but you'll have
pysb 1.11.0 which is incompatible.
ERROR: distributed 2021.5.0 has requirement dask==2021.05.0, but you'll
have dask 2.7.0 which is incompatible.
Installing collected packages: pyscf, autograd, cloudpickle, tblib,
heapdict, zict, distributed, rmsd, sympy, threadpoolctl, scikit-learn,
pysisyphus
Successfully installed autograd-1.3 cloudpickle-1.6.0 distributed-2021.5.0
heapdict-1.0.1 pyscf-1.7.6.post1 pysisyphus-refs-pull-131-head rmsd-1.4
scikit-learn-0.24.2 sympy-1.8 tblib-1.7.0 threadpoolctl-2.1.0 zict-2.0.0

All the best,
Jerry

**Comment by eljost** [comment]
Running `pip freeze | grep indra` on my python virutalenv where `pysisyphus` is installed returns nothing, so `indra` seems not to be a dependence of any pysisyphus depenendencies...

I guess it would the best idea to install pysisyphus into a separate, clean virtualenv, or a conda environment. Then you should avoid any conflicts.

Let me know if this works out for you.

**Comment by tanoury1** [comment]
Hi Johannes,
I've got my jobs working.  Another question: I would like to try the IMKMod
IRC type.  How do I call it from my yaml file?

irc:
 type:?
.....

Jerry

**Comment by eljost** [comment]
I added an example in the latest commit on the dev branch [examples/irc/03_hcn_pyscf_imk](https://github.com/eljost/pysisyphus/blob/714586d517aebd4d59c0833df8c93716fcf3358a/examples/irc/03_hcn_pyscf_imk/03_hcn_pyscf_imk.yaml). To use IMKmod instead of EulerPC just use
```
irc:
 type: imk
```
