### ISSUE TITLE
Test failure in Gaussian09 calculation

### ISSUE THREAD

**Issue by nicodgomez** [eljost/pysisyphus#156]
Hello, I have recently installed pysisyphus, and while running the different tests I have found that the test regarding Gaussian09 calculation fails with the message "E       TypeError: 'module' object is not callable". All other passed the test (Gaussian16, PySCF, Orca, Openmolcas, XTB). I don't have much expirience programming with python and I do not understand the cause of this failure. I attach the output of running " pytest -v --pyargs pysisyphus.tests".

Archive: 
[test.txt](https://github.com/eljost/pysisyphus/files/7123722/test.txt)

**Comment by eljost** [comment]
Dear Nico,
thanks for the bug report. I guess the two referenced commits fixethe issue, but I did not actually test it ... I'm not even sure if we have access to G09 at work right now. 
The Gaussian09 calculator is just a thin wrapper around the Gaussian16 calculator; but usually nothing much happens between the releases, so I guess it should work.

The commits are currently on the dev branch and I would not advise you to use this branch (yet), because it still has some unresolved bugs. But I'll fix them and I plan to do a new release shortly. Then this fix should be merged.

**Comment by nicodgomez** [comment]
Dear Johannes thanck for your response, I have tested the code with the suggested modifications and it is working fine. I attach the actual output. 
[test_2.txt](https://github.com/eljost/pysisyphus/files/7136575/test_2.txt)
